### ISSUE TITLE
mit sphinx 1.3.3 bekomm ich noch diesen fehler

### ISSUE THREAD

**Issue by mal2** [Sawrz/Project-Simulation#1]
/Project-Simulation/PCA/pca.py:docstring of pca.PCA:5: SEVERE: Unexpected section title.

"Attributes:
-----------"

alles was danach kommen soll, muss anscheinend eingerückt werden und die "-----" müssen bei mir weg, dann gibts keinen fehler

**Comment by whllnd** [comment]
hi,

es muss korrekterweise "Attributes" und nicht "Attributes:" heißen. ist 
korrigiert, der fehler dürfte also nicht mehr angezeigt werden.

grüße, malte

Am 18.12.2015 um 16:46 schrieb mal2:
